<a href="https://colab.research.google.com/github/paolopdel/zodiac_chinese/blob/master/Lesson8_17_char_Lev_Rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

In [0]:
# open text file and read in data as `text`
with open('data/Output1.txt', 'r') as f:
    text = f.read()

In [0]:
text[:100]
#len(text)


"\ufeffDoesn't take much to make me happy\nAnd make me smile with glee \nNever never will I feel discouraged"

In [0]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
print(chars)
int2char = dict(enumerate(chars))
print(int2char)
char2int = {ch: ii for ii, ch in int2char.items()}
print(char2int)
# encode the text
encoded = np.array([char2int[ch] for ch in text])
len(chars)


('m', '”', 'é', "'", 'w', 'c', '-', '&', '値', 'S', 'D', 'U', 'f', 'j', '1', '[', 'H', 'n', '"', '“', 'C', 'W', 'B', 'O', 'u', 'ì', 's', '4', 'x', '—', 'y', 'V', '’', '7', 'r', '}', '`', '\n', 'k', ')', 'M', 'q', '貓', 'K', 'i', ' ', '.', 'h', '_', 'R', 'è', 'F', '…', ';', 'd', 'P', 'Q', 'o', '#', 'Y', ',', 't', 'È', '‘', '2', '\\', '\ufeff', '8', 'à', '3', '0', 'z', 'b', 'p', 'v', 'a', '!', 'I', '(', '{', 'l', ':', 'ù', '5', '´', 'T', 'E', '9', '/', 'ç', ']', '\t', '?', '6', 'e', '~', 'A', 'Z', 'ã', 'G', 'J', 'g', 'N', '王', 'L')
{0: 'm', 1: '”', 2: 'é', 3: "'", 4: 'w', 5: 'c', 6: '-', 7: '&', 8: '値', 9: 'S', 10: 'D', 11: 'U', 12: 'f', 13: 'j', 14: '1', 15: '[', 16: 'H', 17: 'n', 18: '"', 19: '“', 20: 'C', 21: 'W', 22: 'B', 23: 'O', 24: 'u', 25: 'ì', 26: 's', 27: '4', 28: 'x', 29: '—', 30: 'y', 31: 'V', 32: '’', 33: '7', 34: 'r', 35: '}', 36: '`', 37: '\n', 38: 'k', 39: ')', 40: 'M', 41: 'q', 42: '貓', 43: 'K', 44: 'i', 45: ' ', 46: '.', 47: 'h', 48: '_', 49: 'R', 50: 'è', 51: 'F', 52: '…

105

In [0]:
encoded[:100]

array([ 66,  10,  57,  94,  26,  17,   3,  61,  45,  61,  75,  38,  94,
        45,   0,  24,   5,  47,  45,  61,  57,  45,   0,  75,  38,  94,
        45,   0,  94,  45,  47,  75,  73,  73,  30,  37,  96,  17,  54,
        45,   0,  75,  38,  94,  45,   0,  94,  45,  26,   0,  44,  80,
        94,  45,   4,  44,  61,  47,  45, 101,  80,  94,  94,  45,  37,
       102,  94,  74,  94,  34,  45,  17,  94,  74,  94,  34,  45,   4,
        44,  80,  80,  45,  77,  45,  12,  94,  94,  80,  45,  54,  44,
        26,   5,  57,  24,  34,  75, 101,  94,  54])

In [0]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    

#crea un array: 3 con aggiuna 8 (3,8)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.

    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot


In [0]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)
#print(test_seq)   #[[3 5 1]]
#print(test_seq.shape)#(1, 3)
#print(test_seq.size)   #3
#print(test_seq.flatten())  #[3 5 1]
#print(test_seq) #[[3 5 1]]
#arange che si trova nel codice sopra è come for, ma parte da dove si vuole, primo argomento, passo nel secondo arg.
#l'array 3,5,1 viene posto come primo arg. 

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [0]:
#starting sequence: [1 2 3 4 5 6 7 8 9 10 11 12]
#Batch size: 2   [1 2 3 4 5 6 ]
#               [7 8 9 10 11 12]
#sequence lenght: 3  [1 2 3 ......
#                    [7 8 9 ......


In [0]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    batch_size_total = batch_size * seq_length
    # total number of batches we can make
    n_batches = len(arr)//batch_size_total
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size_total]
    # Reshape into batch_size rows
    arr = arr.reshape((batch_size, -1))
    
    # iterate through the array, one sequence at a time
    for n in range(0, arr.shape[1], seq_length):
        # The features
        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

In [0]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)
print(batches)
1985223//400

<generator object get_batches at 0x7fa29d027e08>


4963

In [0]:
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[14 52 38  1  4 27 78 39 76 49]
 [21  5 80 39  4 52 38  4 39 38]
 [27 80 18 39  5 78 39 38 39 33]
 [21 39  4 52 27 39 43 52 12 27]
 [39 21 38 69 39 52 27 78 39  4]
 [43 64 21 21 12  5 80 39 38 80]
 [39 55 80 80 38 39 52 38 18 39]
 [58  8 16  5 80 21  0 15 77 39]]

y
 [[52 38  1  4 27 78 39 76 49 49]
 [ 5 80 39  4 52 38  4 39 38  4]
 [80 18 39  5 78 39 38 39 33  5]
 [39  4 52 27 39 43 52 12 27 33]
 [21 38 69 39 52 27 78 39  4 27]
 [64 21 21 12  5 80 39 38 80 18]
 [55 80 80 38 39 52 38 18 39 21]
 [ 8 16  5 80 21  0 15 77 39 79]]


In [0]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

Training on GPU!


In [0]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the LSTM
        self.lstm = nn.LSTM(len(self.chars), n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        ## TODO: define a dropout layer
        self.dropout = nn.Dropout(drop_prob)
        
        ## TODO: define the final, fully-connected output layer
        self.fc = nn.Linear(n_hidden, len(self.chars))
      
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        r_output, hidden = self.lstm(x, hidden)
        
        ## TODO: pass through a dropout layer
        out = self.dropout(r_output)
        
        # Stack up LSTM outputs using view
        # you may need to use contiguous to reshape the output
        out = out.contiguous().view(-1, self.n_hidden)
        
        ## TODO: put x through the fully-connected layer
        out = self.fc(out)
        
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                      weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden
        

In [0]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            #h = tuple([each.data for each in h])
            h = tuple([each.data for each in h])
            #print(h)
            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.view(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                   
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))



In [0]:
# define and print the net
n_hidden=512
n_layers=2

net = CharRNN(chars, n_hidden, n_layers)
print(net.chars)
len(net.chars)


('m', '”', 'é', "'", 'w', 'c', '-', '&', '値', 'S', 'D', 'U', 'f', 'j', '1', '[', 'H', 'n', '"', '“', 'C', 'W', 'B', 'O', 'u', 'ì', 's', '4', 'x', '—', 'y', 'V', '’', '7', 'r', '}', '`', '\n', 'k', ')', 'M', 'q', '貓', 'K', 'i', ' ', '.', 'h', '_', 'R', 'è', 'F', '…', ';', 'd', 'P', 'Q', 'o', '#', 'Y', ',', 't', 'È', '‘', '2', '\\', '\ufeff', '8', 'à', '3', '0', 'z', 'b', 'p', 'v', 'a', '!', 'I', '(', '{', 'l', ':', 'ù', '5', '´', 'T', 'E', '9', '/', 'ç', ']', '\t', '?', '6', 'e', '~', 'A', 'Z', 'ã', 'G', 'J', 'g', 'N', '王', 'L')


105

In [0]:
#batch_size = 128
#seq_length = 100
#n_epochs = 20 # start smaller if you are just testing initial behavior

batch_size = 128
seq_length = 100
n_epochs = 20 # start smaller if you are just testing initial behavior lr=0.001

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)

Epoch: 1/20... Step: 10... Loss: 3.2779... Val Loss: 3.3059
Epoch: 1/20... Step: 20... Loss: 3.2103... Val Loss: 3.2270
Epoch: 1/20... Step: 30... Loss: 3.1721... Val Loss: 3.2071
Epoch: 1/20... Step: 40... Loss: 3.1649... Val Loss: 3.2027
Epoch: 1/20... Step: 50... Loss: 3.1333... Val Loss: 3.2007
Epoch: 1/20... Step: 60... Loss: 3.1541... Val Loss: 3.1981
Epoch: 2/20... Step: 70... Loss: 3.1415... Val Loss: 3.1885
Epoch: 2/20... Step: 80... Loss: 3.1264... Val Loss: 3.1798
Epoch: 2/20... Step: 90... Loss: 3.0902... Val Loss: 3.1428
Epoch: 2/20... Step: 100... Loss: 3.0068... Val Loss: 3.0698
Epoch: 2/20... Step: 110... Loss: 2.8855... Val Loss: 2.9292
Epoch: 2/20... Step: 120... Loss: 2.7386... Val Loss: 2.8211
Epoch: 3/20... Step: 130... Loss: 2.6263... Val Loss: 2.7040
Epoch: 3/20... Step: 140... Loss: 2.5291... Val Loss: 2.6077
Epoch: 3/20... Step: 150... Loss: 2.4317... Val Loss: 2.5300
Epoch: 3/20... Step: 160... Loss: 2.3426... Val Loss: 2.4877
Epoch: 3/20... Step: 170... Loss:

In [0]:
# change the name, for saving multiple files
model_name = 'rnn_20_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

In [0]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        #print(x)
        x = one_hot_encode(x, len(net.chars))
        #print(x)
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            #print(top_ch)
            #print(p.topk(top_k))
            top_ch = top_ch.numpy().squeeze()
            #print(top_ch)
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        #print(char)
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

In [0]:
def sample(net, size, prime='Chapter', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [0]:
print(sample(net, 1000, prime='Chapter', top_k=5))

NameError: ignored